### ISSUE TITLE
Add an emoji legend to README

### ISSUE THREAD

**Issue by zacjones93** [eggheadio-projects/build-an-app-with-the-AWS-cloud-development-kit-notes#2]
We are using emojis to signify types of notes but don't have a legend posted so learners know what emoji's are signifying

**Comment by edieblu** [comment]
Hiya @zacjones93 sorry just saw this now 😃 The emoji legend is in the intro file, let me know if that's ok. 

Same place as [in the first notes I did ](https://github.com/eggheadio-projects/develop-accessible-web-apps-with-react-notes/blob/master/00-intro.md)- where the emoji legend originates from 👍 And also [here](https://github.com/eggheadio-projects/building-a-serverless-jamstack-todo-app-with-netlify-gatsby-graphql-and-faunadb/blob/master/00-intro-and-welcome.md).

Let me know if you need me to move the 3 of them, not a problem at all 😃

**Comment by zacjones93** [comment]
What do you think of promoting it to the README? Thinking about the instances where learners check out a few specific files and might miss it in the intro

**Comment by edieblu** [comment]
> @edieblu What do you think of promoting it to the README? Thinking about the instances where learners check out a few specific files and might miss it in the intro

Heya @zacjones93 for sure, I can move it! 👍 Shall I do it for the other two course notes as well?

**Comment by edieblu** [comment]
Heya @zacjones93 just created a [PR](https://github.com/eggheadio-projects/build-an-app-with-the-AWS-cloud-development-kit-notes/pull/3) 👍
