### ISSUE TITLE
new s3.Bucket initialize scope problem

### ISSUE THREAD

**Issue by MrZakos** [eggheadio-projects/build-an-app-with-the-AWS-cloud-development-kit-notes#25]
Hi,

in your example,the first argument for `new s3.bucket` constructor  is of type  `cdk.Construct` but with my version its just `Construct `which causes the code to fail

```
    const logoBucket = new s3.Bucket(this, "LogoBucket", {
      // we will fill this out later
    });
```

![image](https://user-images.githubusercontent.com/999613/85224155-d832d180-b3d0-11ea-9a6c-2a3e2d32d8b3.png)

what's wrong? 
🙏

**Comment by laurosilvacom** [comment]
@MrZakos you need to ensure that all CDK packages (core, s3, etc.) have the same version. The recommended version for all CDK packages is `1.31.0`.

You can install an old version of an npm package using the `@` syntax:

```
npm install <package>@<version>
```
```
npm i @aws-cdk/aws-s3@1.31.0
```

**Comment by zacjones93** [comment]
@all-contributor please add @MrZakos for bug

**Comment by zacjones93** [comment]
@all-contributors please add @MrZakos for bug
